server:
  port: 8082
  servlet:
    context-path: /api/shibing-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shibing?useSSL=false&characterEncoding=utf8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: intern_server.shibing.data.po
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: trye
  params: count=countSql