sb:
  # 名称
  name: shibin
  # 版本
  version: 2.2.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: F:/sb/uploadPath
  # 获取ip地址开关
  addressEnabled: true
server:
  port: 8082
  servlet:
    context-path: /api/shibing-service
spring:
  http:
    converters:
      preferred-json-mapper: fastjson      # HTTP消息转换时优先使用JSON映射器。
    encoding:
      force: true                      # 强制将HTTP请求和响应编码为所配置的字符集。
  datasource:
    url: jdbc:mysql://58.87.77.191:3306/shibing?useSSL=false&characterEncoding=utf8
    password: Wjy@018080
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: intern_server.shibing.data.po
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#Redis配置
redisProperties:
  REDIS_MAX_TOTAL: 50              # 连接池最大连接数（使用负值表示没有限制）
  REDIS_MAX_WAIT: -1               # 连接池最大阻塞等待时间（使用负值表示没有限制）
  REDIS_MAX_IDLE: 50               # 连接池中的最大空闲连接
  REDIS_HOST: 58.87.77.191           # Redis服务器地址
  REDIS_PORT: 6379                 # Redis服务器连接端口
  REDIS_TIMEOUT: 200000            # 连接超时时间（毫秒）
  REDIS_USE_PASSWORD: Y            # 是否需要密码
  REDIS_PASSWORD: Wjy@018080      # Redis服务器连接密码（默认为空）

noticeType:
  show: false